package es.studium.adtema3practicahibernate;
// Generated 17 nov 2021 10:34:56 by Hibernate Tools 5.5.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table (name = "clientes", schema="hotel")
public class Clientes implements java.io.Serializable {
	/**
	 * Anka Motz
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	
	@Column (name ="idCliente")
	private Integer idCliente;
	
	@Column 
	private String nombre;
	
	@Column
	private String apellidos;
	
	@Column
	private String email;
	
	@Column
	private String dni;
	
	@Column
	private String clave;

	public Clientes() {
	}
	public Clientes(Integer IdCliente) {
		this.idCliente = IdCliente;
	}
	public Clientes(String apellidosCliente) {
		this.apellidos = apellidosCliente; 
	}
	
	public Clientes(String nombreCliente, String apellidosCliente, String emailCliente, String dniCliente,
			String claveCliente) {
		this.nombre = nombreCliente;
		this.apellidos = apellidosCliente;
		this.email = emailCliente;
		this.dni = dniCliente;
		this.clave = claveCliente;
	}
	public Clientes(Integer Id, String nombreCliente, String apellidosCliente, String emailCliente, String dniCliente,
			String claveCliente) {
		this.idCliente = Id;
		this.nombre = nombreCliente;
		this.apellidos = apellidosCliente;
		this.email = emailCliente;
		this.dni = dniCliente;
		this.clave = claveCliente;
	}
	

	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	public String getNombreCliente() {
		return this.nombre;
	}

	public void setNombreCliente(String nombreCliente) {
		this.nombre = nombreCliente;
	}

	public String getApellidosCliente() {
		return this.apellidos;
	}

	public void setApellidosCliente(String apellidosCliente) {
		this.apellidos = apellidosCliente;
	}

	public String getEmailCliente() {
		return this.email;
	}

	public void setEmailCliente(String emailCliente) {
		this.email = emailCliente;
	}

	public String getDniCliente() {
		return this.dni;
	}

	public void setDniCliente(String dniCliente) {
		this.dni = dniCliente;
	}

	public String getClaveCliente() {
		return this.clave;
	}

	public void setClaveCliente(String claveCliente) {
		this.clave = claveCliente;
	}

}
